name: core_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  go_router: ^17.0.1
  google_fonts: ^6.2.1
  supabase_flutter: ^2.12.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  file_picker: ^8.0.0+1
  record: ^5.1.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
